/** Movement patterns we can illustrate. Kept in its own file so schemas can import it cheaply. */
export const PATTERN_IDS = [
  "squat",
  "hinge",
  "lunge",
  "leg_press",
  "leg_extension",
  "leg_curl_seated",
  "leg_curl_lying",
  "hip_thrust",
  "hip_abduction",
  "calf_raise",
  "bench_press",
  "incline_press",
  "chest_fly",
  "push_up",
  "dip",
  "overhead_press",
  "lateral_raise",
  "face_pull",
  "bent_row",
  "seated_row",
  "pulldown",
  "pull_up",
  "curl",
  "pushdown",
  "overhead_triceps",
  "skullcrusher",
  "crunch",
  "plank",
  "leg_raise",
] as const;

export type PatternId = (typeof PATTERN_IDS)[number];
